### PR TITLE
Kbyogo

### PR DESCRIPTION
**Pull request by TennisSprinterkb**
Hey everyone so everything should be up and working, when running the application on your computer 
you should use **npm run dev** not npm start

### CODE REVIEW

**Review by ebeaudet — APPROVED** [review]
looks great

**Comment by ebeaudet** [comment]
looks good

**Comment by lilysimmons** [comment]
great

**Comment by jhorowitz96** [comment]
Looks good

**Review by jhorowitz96 — APPROVED** [review]
looks good to me

**Pull request merged**
